# Coze 配置
coze.api.token=cztei_hNVn76y1kKbh1FAQW2QygnY4C6i0hMmz4JN4mjbHZNgmtgA9BtYefpyIG3SMLvbZL
coze.api.botId=7620663401027026990
coze.api.url=https://api.coze.cn/v1/bot/get_online_info

# 数据库配置（根据你的 Navicat 连接信息填写）
spring.datasource.url=jdbc:mysql://localhost:3306/offer100?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456